import { cookies } from "next/headers";
import { db, withDatabaseRetry } from "@/lib/db";
import { hashToken } from "@/lib/security";

/**
 * Nominations are self-service: every candidate opens the same `/nominate` link
 * rather than a per-candidate link generated by an administrator. The only thing
 * the Election Committee controls is the window that link accepts entries in.
 *
 * A candidate identifies themselves once, and the resulting NominationInvite row
 * is bound to their browser by this cookie. The row still carries a tokenHash, so
 * draft autosave, private file uploads and submission all keep working unchanged —
 * the token is simply issued to the candidate now instead of by an administrator.
 */
export const NOMINATION_COOKIE = "nomination_session";

export type NominationWindowState = "open" | "upcoming" | "closed";

export function nominationWindowState(
  opensAt: Date | null,
  closesAt: Date | null,
  now = new Date(),
): NominationWindowState {
  if (!opensAt || !closesAt) return "closed";
  if (now < opensAt) return "upcoming";
  if (now > closesAt) return "closed";
  return "open";
}

/** The election nominations are collected for, with its window and open positions. */
export async function getNominationElection() {
  return withDatabaseRetry(() => db.election.findFirst({
    where: { status: "PUBLISHED" },
    orderBy: { opensAt: "desc" },
    select: {
      id: true,
      title: true,
      nominationsOpenAt: true,
      nominationsCloseAt: true,
      positions: {
        orderBy: { sortOrder: "asc" },
        select: { id: true, title: true, slug: true, sortOrder: true },
      },
    },
  }));
}

/** The nomination bound to the caller's browser, or null when there is no session. */
export async function currentNomination() {
  const token = (await cookies()).get(NOMINATION_COOKIE)?.value;
  if (!token) return null;
  return withDatabaseRetry(() => db.nominationInvite.findUnique({
    where: { tokenHash: hashToken(token) },
    include: { position: true, guarantors: { orderBy: { createdAt: "asc" } } },
  }));
}

/** A nomination can still be edited while it is a draft (or was sent back for correction). */
export function isEditable(
  invite: { status: string; expiresAt: Date } | null | undefined,
) {
  return Boolean(
    invite && ["DRAFT", "REJECTED"].includes(invite.status) && invite.expiresAt > new Date(),
  );
}
